on:
  schedule:
    - cron: '30 0 * * *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the app url
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://lbotano-fso-pokedex.herokuapp.com/health
